qmessages/urls.py
from django.urls import path
from qmessages import views

app_name = "qmessages"

urlpatterns = [

    path('message/create/', views.MessageCreateView.as_view(), name='message_create_view'),
    path('message/list/', views.MessageListView.as_view(), name='message_list_view'),
    path('message/detail/', views.MessageDetailView.as_view(), name='message_detail_view'),
    path('message/detail/<str:token>/', views.MessageDetailView.as_view(), name='message_detail_view_with_token'),
    path('message/detail/<str:token>/<int:parent_reply>/', views.MessageDetailView.as_view(), name='message_detail_view_with_token_and_parent_reply'),
    path('message/update/', views.MessageUpdateView.as_view(), name='message_update_view'),
    path('message/update/<str:token>/', views.MessageUpdateView.as_view(), name='message_update_view_with_token'),
    path('message/update/status/', views.MessageStatusUpdateView.as_view(), name='message_status_update_view'),
    path('message/delete/<str:token>/', views.MessageDeleteView.as_view(), name='message_delete_view'),
    path('message/reply/create/', views.MessageReplyCreateView.as_view(), name='message_reply_create_view'),
    path('message/reply/create/<str:token>/', views.MessageReplyCreateView.as_view(), name='message_reply_create_view_with_token'),
    path('message/reply/create/<str:token>/<int:parent_reply>/', views.MessageReplyCreateView.as_view(), name='message_reply_create_view_with_token'),
    path('message/reply/update/<int:pk>/', views.MessageReplyUpdateView.as_view(), name='message_reply_update_view'),
    path('message/reply/detail/<int:pk>/', views.MessageReplyDetailView.as_view(), name='message_reply_detail_view'),
    path('message/reply/delete/<int:pk>/', views.MessageReplyDeleteView.as_view(), name='message_reply_delete_view'),
    path('note/create/', views.NoteCreateView.as_view(), name='note_create_view'),
]

qmessages/models.py
import uuid
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.conf import settings


class BaseModel(models.Model):
    deleted = models.BooleanField(default=False)
    all_objects = models.Manager()

    class Meta:
        abstract = True

    def delete(self):
        self.deleted = True
        self.save()
    
    def hard_delete(self):
        super().delete()

class BaseModelManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)
   
class Message(BaseModel):
    token = models.UUIDField(default=uuid.uuid4, editable=False)
    project = models.CharField(max_length=255, null=True)
    app = models.CharField(max_length=255, null=True)
    model = models.CharField(max_length=255, null=True)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="message_sender", on_delete=models.CASCADE)
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="message_receiver", on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    text = models.TextField()
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated at"), auto_now=True)
    
    objects = BaseModelManager()

  
    def __str__(self):
        return f"{self.subject} - {str(self.token)}"

class MessageStatusDesc(models.Model):
    desc = models.CharField(_("desc"), max_length=255)
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated at"), auto_now=True)

    def __str__(self):
        return 'Desc: {}'.format(self.desc)
    
class MessageStatus(models.Model): 
    message_desc = models.ForeignKey(MessageStatusDesc,related_name="messagestatus_messagestatusdesc", verbose_name=_("message desc"), on_delete=models.CASCADE)
    message = models.ForeignKey(Message, related_name="message_status", verbose_name=_("message"), on_delete=models.CASCADE)
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated at"), auto_now=True)

    def __str__(self):
        return 'Message Status: {} - Status Date: {} - Updated On: {}'.format(self.message_desc.desc, self.created_at, self.updated_at)

    def next_status(self):
        status_list = list(MessageStatusDesc.objects.values_list('desc', flat=True))
        current_status_index = status_list.index(self.message_desc.desc)
        if current_status_index < len(status_list) - 1:
            next_status_desc = status_list[current_status_index + 1]
            next_status = MessageStatusDesc.objects.get(desc=next_status_desc)
            self.message_desc = next_status
            self.save()

class MessageReply(BaseModel):
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    parent_reply = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated at"), auto_now=True)
    replier = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    objects = BaseModelManager()

    def delete(self):
        children = MessageReply.objects.filter(parent_reply=self)
        for child in children:
            child.delete()
        super().delete()

    def hard_delete(self):
        MessageReply.objects.filter(parent_reply=self).delete()
        super().hard_delete()

    def __str__(self):
        return f"Id: {self.id} {self.text} - {str(self.message.token)}"

class MessageReplyStatus(models.Model): 
    message_desc = models.ForeignKey(MessageStatusDesc,related_name="messagereplystatus_messagestatusdesc", verbose_name=_("message desc"), on_delete=models.CASCADE)
    message_reply = models.ForeignKey(MessageReply, related_name="message_reply_status", verbose_name=_("message reply"), on_delete=models.CASCADE)
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated at"), auto_now=True)

    def __str__(self):
        return 'Message Status: {} - Status Date: {} - Updated On: {}'.format(self.message_desc.desc, self.created_at, self.updated_at)

    def next_status(self):
        status_list = list(MessageStatusDesc.objects.values_list('desc', flat=True))
        current_status_index = status_list.index(self.message_desc.desc)
        if current_status_index < len(status_list) - 1:
            next_status_desc = status_list[current_status_index + 1]
            next_status = MessageStatusDesc.objects.get(desc=next_status_desc)
            self.message_desc = next_status
            self.save()

class Note(BaseModel):
    token = models.UUIDField(default=uuid.uuid4, editable=False)
    project = models.CharField(max_length=255, null=True)
    app = models.CharField(max_length=255, null=True)
    model = models.CharField(max_length=255, null=True)
    text = models.TextField()
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated at"), auto_now=True)
    
    objects = BaseModelManager()

    def __str__(self):
        return f"{self.text[:50]} - {str(self.token)}"

qmessages/templates/message_content_create.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>

qmessages/templates/message_create.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>

qmessages/templates/message_delete.html
{% block content %}
  <h1>Delete Message</h1>
  <p>Are you sure you want to delete this message?</p>
  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
  </form>
{% endblock %}

qmessages/templates/message_detail.html
<h1>Message Detail</h1>

<div>
    {% csrf_token %}
    <p>Message: {{ object.text }}</p>
    <p>Create at: {{ object.created_at }}</p>
    <p>Updated at: {{ object.updated_at }}</p>
</div>    

qmessages/templates/message_list.html
<h1>Message Module</h1>

<h2>Sent Messages</h2>
<ul>
    {% for object in object_list %}
        {% if object.sender == request.user %}
        <li>
            <table>
                <tr>
                    <th>Text</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th>Status</th>
                </tr>
                <tr>
                    <td>{{ object.text }}</td>
                    <td>{{ object.created_at }}</td>
                    <td>{{ object.updated_at }}</td>
                    <td>{{ object.message_status.last.message_desc.desc }}</td>
    
                </tr>
            </table>
    
            <a href="{% url 'qmessages:message_reply_create_view_with_token' object.token %}">Reply</a>
            
            {% if object.sender == request.user %}
                <a href="{% url 'qmessages:message_update_view_with_token' object.token %}">Update</a>
            {% endif %}

            <a href="{% url 'qmessages:message_detail_view_with_token' object.token %}">Detail</a>

            <a href="{% url 'qmessages:message_delete_view' object.token %}">Delete</a>
    
            <h2>Replies</h2>
            {% for reply in object.messagereply_set.all %}
                {% if not reply.parent_reply %}
                <!-- Display the reply -->
                <p>ID: {{ reply.id }}</p>
                <p>Reply: {{ reply.text }}</p>
                <p>Replier: {{ reply.replier }}</p>
                <p>Created at: {{ reply.created_at }}</p>
                <p>Updated at: {{ reply.updated_at }}</p>
                <td>Status: {{ reply.message_reply_status.last.message_desc.desc }}</td>
    
                <a href="{% url 'qmessages:message_reply_create_view_with_token' token=object.token parent_reply=reply.id %}">Reply</a>
    
                {% if reply.replier == request.user %}
                    <a href="{% url 'qmessages:message_reply_update_view' reply.pk %}">Update</a>
                {% endif %}

                <a href="{% url 'qmessages:message_detail_view_with_token_and_parent_reply' token=object.token parent_reply=reply.id %}">Detail</a>

                <a href="{% url 'qmessages:message_reply_delete_view' reply.pk %}">Delete</a>

                {% include 'reply_list.html' with replies=reply.messagereply_set.all %}
                {% endif %}
            {% empty %}
                <li>No replies yet.</li>
            {% endfor %}
        </li>
        {% endif %}
    {% empty %}
        <li>No sent messages found.</li>
    {% endfor %}
</ul>

<h2>Received Messages</h2>
<ul>
    {% for object in object_list %}
        {% if object.receiver == request.user %}
        <li>
            <table>
                <tr>
                    <th>Text</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th>Status</th>
                </tr>
                <tr>
                    <td>{{ object.text }}</td>
                    <td>{{ object.created_at }}</td>
                    <td>{{ object.updated_at }}</td>
                    <td>{{ object.message_status.last.message_desc.desc }}</td>
    
                </tr>
            </table>
    
           
            <a href="{% url 'qmessages:message_reply_create_view_with_token' object.token %}">Reply</a>
    
           
            {% if object.sender == request.user %}
                <a href="{% url 'qmessages:message_update_view_with_token' object.token %}">Update</a>
            {% endif %}

            
            <a href="{% url 'qmessages:message_detail_view_with_token' object.token %}">Detail</a>

            <a href="{% url 'qmessages:message_delete_view' object.token %}">Delete</a>
    
            <h2>Replies</h2>
            {% for reply in object.messagereply_set.all %}
                {% if not reply.parent_reply %}
                <!-- Display the reply -->
                <p>ID: {{ reply.id }}</p>
                <p>Reply: {{ reply.text }}</p>
                <p>Replier: {{ reply.replier }}</p>
                <p>Created at: {{ reply.created_at }}</p>
                <p>Updated at: {{ reply.updated_at }}</p>
                <td>Status: {{ reply.message_reply_status.last.message_desc.desc }}</td>
                
                <a href="{% url 'qmessages:message_reply_create_view_with_token' token=object.token parent_reply=reply.id %}">Reply</a>
                
                {% if reply.replier == request.user %}
                    <a href="{% url 'qmessages:message_reply_update_view' reply.pk %}">Update</a>
                {% endif %}

                <a href="{% url 'qmessages:message_detail_view_with_token_and_parent_reply' token=object.token parent_reply=reply.id %}">Detail</a>

                <a href="{% url 'qmessages:message_reply_delete_view' reply.pk %}">Delete</a>
    
                <!-- Display all child replies of this reply -->
                {% include 'reply_list.html' with replies=reply.messagereply_set.all %}
                {% endif %}
            {% empty %}
                <li>No replies yet.</li>
            {% endfor %}
        </li>
        {% endif %}
    {% empty %}
        <li>No received messages found.</li>
    {% endfor %}
</ul>

qmessages/templates/message_reply_create.html
<form id="reply-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

qmessages/templates/message_reply_detail.html
<h1>Message Detail</h1>

<div>
    <p>Message: {{ object.text }}</p>
    <p>Created at: {{ object.created_at }}</p>
    <p>Updated at: {{ object.updated_at }}</p>
</div>

qmessages/templates/message_reply_update.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Message</button>
</form>

qmessages/templates/message_update.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Message</button>
</form>

qmessages/templates/note_create.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>

qmessages/templates/reply_list.html
<ul>
    {% for reply in replies %}
        <li>
            <p>ID: {{ reply.id }}</p>
            <p>Reply: {{ reply.text }}</p>
            <p>Replier: {{ reply.replier }}</p>
            <p>Created at: {{ reply.created_at }}</p>
            <p>Updated at: {{ reply.updated_at }}</p>
            <td>Status: {{ reply.message_reply_status.last.message_desc.desc }}</td>

            <a href="{% url 'qmessages:message_reply_create_view_with_token' token=object.token parent_reply=reply.id %}">Reply</a>

            {% if reply.replier == request.user %}
                <a href="{% url 'qmessages:message_reply_update_view' reply.pk %}">Update</a>
            {% endif %}

            <a href="{% url 'qmessages:message_detail_view_with_token_and_parent_reply' token=object.token parent_reply=reply.id %}">Detail</a>
            
            <a href="{% url 'qmessages:message_reply_delete_view' reply.pk %}">Delete</a>

            {% include 'reply_list.html' with replies=reply.messagereply_set.all %}
        </li>
    {% endfor %}
</ul>